#ifndef CONFIGURATION_ADV_H
#define CONFIGURATION_ADV_H
#if 0
#define ADVANCED_OK
#define AXIS_RELATIVE_MODES {false, false, false, false}
#define BED_CHECK_INTERVAL 5000
#define BED_HYSTERESIS 5
#define BLOCK_BUFFER_SIZE 32
#define BUFSIZE 16
#define CONFIGURATION_ADV_H_VERSION 010109
#define DEFAULT_MINIMUMFEEDRATE       0.0     // minimum feedrate
#define DEFAULT_MINSEGMENTTIME        20000
#define DEFAULT_MINTRAVELFEEDRATE     0.0
#define DEFAULT_STEPPER_DEACTIVE_TIME 30
#define EMERGENCY_PARSER
#define FASTER_GCODE_PARSER
#define HOMING_BUMP_DIVISOR { 2, 2, 4 }
#define INVERT_E_STEP_PIN false
#define INVERT_X_STEP_PIN false
#define INVERT_Y_STEP_PIN false
#define INVERT_Z_STEP_PIN false
#define MAXIMUM_STEPPER_RATE 500000
#define MAX_CMD_SIZE 64
#define MICROSTEP_MODES { 16, 16, 16, 16, 16 }
#define MINIMUM_PLANNER_SPEED 0.05
#define MINIMUM_STEPPER_DIR_DELAY 200
#define MINIMUM_STEPPER_PULSE 1
#define MIN_STEPS_PER_SEGMENT 16
#define NO_TIMEOUTS 1000
#define NO_VOLUMETRICS
#define PROPORTIONAL_FONT_RATIO 1.0
#define QUICK_HOME
#define RX_BUFFER_SIZE 1024
#define SERIAL_XON_XOFF
#define THERMAL_PROTECTION_BED_HYSTERESIS 5
#define THERMAL_PROTECTION_BED_PERIOD 60
#define THERMAL_PROTECTION_HYSTERESIS 10
#define THERMAL_PROTECTION_PERIOD 45
#define TX_BUFFER_SIZE 128
#define WATCH_BED_TEMP_INCREASE 2
#define WATCH_BED_TEMP_PERIOD 120
#define WATCH_TEMP_INCREASE 4
#define WATCH_TEMP_PERIOD 40
#define X_HOME_BUMP_MM 5
#define Y_HOME_BUMP_MM 5
#define Z_HOME_BUMP_MM 1
#endif
#endif//!CONFIGURATION_ADV_H
